version: 2
updates:
    -   package-ecosystem: maven
        directory: /
        schedule:
            interval: daily
            time: "06:00"
            timezone: America/New_York
        assignees:
            - dsingley

    -   package-ecosystem: github-actions
        directory: /
        schedule:
            interval: daily
            time: "06:00"
            timezone: America/New_York
        assignees:
            - dsingley
