package spark.examples.hello;

import static spark.Spark.get;
import static spark.Spark.secure;

import spark.util.SparkTestUtil;

/**
 * Run with no arguments to use a self-signed cert generated by {@link SparkTestUtil}, or
 * supply your own keystore path as arg 0 and its password as arg 1.
 */
public class HelloSecureWorld {
    public static void main(String[] args) {

        if (args.length == 0) {
            secure(SparkTestUtil.getKeyStoreLocation(), SparkTestUtil.getKeystorePassword(), null, null);
            System.out.println("""
                    Using generated keystore: %s

                    Try: curl --cacert %s https://localhost:4567/hello"""
                    .formatted(SparkTestUtil.getKeyStoreLocation(), SparkTestUtil.getCaCertificateLocation()));
        } else if (args.length == 2) {
            secure(args[0], args[1], null, null);
        } else {
            System.err.println("Usage: HelloSecureWorld [keystoreFile keystorePassword]");
            System.exit(1);
            return;
        }

        get("/hello", (request, response) -> {
            return "Hello Secure World!";
        });

    }
}
